// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGDI_fO0uIfeBy-9Yspy7txnLtR1THs8',
    appId: '1:112628763044:web:c21677f230d12f95b1d931',
    messagingSenderId: '112628763044',
    projectId: 'timetracker-2ee25',
    authDomain: 'timetracker-2ee25.firebaseapp.com',
    storageBucket: 'timetracker-2ee25.appspot.com',
    measurementId: 'G-T6CTRKF6J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxjYXsvprjXEe6ip6l9_K9Mlm6NaF_fA',
    appId: '1:112628763044:android:aec6405baa82cc5bb1d931',
    messagingSenderId: '112628763044',
    projectId: 'timetracker-2ee25',
    storageBucket: 'timetracker-2ee25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfqOvmM3qtNb2Q73WCDIpUF6z4ZJPP9js',
    appId: '1:112628763044:ios:1a5dc7fae2fe526cb1d931',
    messagingSenderId: '112628763044',
    projectId: 'timetracker-2ee25',
    storageBucket: 'timetracker-2ee25.appspot.com',
    iosBundleId: 'com.example.individualproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfqOvmM3qtNb2Q73WCDIpUF6z4ZJPP9js',
    appId: '1:112628763044:ios:21d953f53381fea9b1d931',
    messagingSenderId: '112628763044',
    projectId: 'timetracker-2ee25',
    storageBucket: 'timetracker-2ee25.appspot.com',
    iosBundleId: 'com.example.individualproject.RunnerTests',
  );
}
